# Generated by Django 3.2.11 on 2022-01-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20220129_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.task'),
        ),
    ]
