# Generated by Django 3.2.11 on 2022-01-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
            preserve_default=False,
        ),
    ]
